# ==============================================================================
# Study 47 Wave 1 eligibility check using the claims CSV only
# Generated by ChatGPT for the Bayesian reanalysis project.
#
# Purpose:
#   Assess whether study_47_claim_01 is eligible for Wave 1 using the model
#   metadata and reported statistics stored in claims (1).csv. No participant-
#   level raw data are required or assumed to be available.
#
# Important limitation:
#   This script verifies structural and algebraic equivalence from the recorded
#   model specification and summary statistics. It cannot independently rerun
#   the original mixed ANOVA or reconstruct participant-level marginal means.
#
# Outputs:
#   1. study_47_target_record.csv
#   2. study_47_wave1_metadata_checks.csv
#   3. study_47_wave1_metadata_summary.txt
# ==============================================================================

options(stringsAsFactors = FALSE)

# ------------------------------- User settings --------------------------------

project_root <- "/Users/xiaoyixu/Documents/文稿 - Xiaoyi的MacBook Pro/UBristol 2026 Summer/Wave1_Validation"
claims_path <- file.path(project_root, "Data/claims.csv")
output_dir <- file.path(project_root, "Outputs", "validation", "study_47")
target_claim_id <- "study_47_claim_01"
tolerance <- 1e-10

# ------------------------------ Helper functions ------------------------------

stop_with_message <- function(...) {
  stop(paste0(...), call. = FALSE)
}

require_columns <- function(data, required, object_name) {
  missing_columns <- setdiff(required, names(data))
  if (length(missing_columns) > 0L) {
    stop_with_message(
      object_name,
      " is missing the following required columns: ",
      paste(missing_columns, collapse = ", ")
    )
  }
}

as_logical_value <- function(x) {
  if (is.logical(x)) return(isTRUE(x))
  tolower(trimws(as.character(x))) %in% c("true", "t", "1", "yes")
}

as_numeric_value <- function(x, name) {
  value <- suppressWarnings(as.numeric(x))
  if (length(value) != 1L || is.na(value)) {
    stop_with_message("Could not read a numeric value for ", name, ".")
  }
  value
}

approximately_equal <- function(x, y, tolerance_value = tolerance) {
  isTRUE(all.equal(
    as.numeric(x),
    as.numeric(y),
    tolerance = tolerance_value,
    check.attributes = FALSE
  ))
}

format_number <- function(x, digits = 12L) {
  format(
    as.numeric(x),
    digits = digits,
    scientific = FALSE,
    trim = TRUE
  )
}

write_lines_utf8 <- function(lines, path) {
  connection <- file(path, open = "wt", encoding = "UTF-8")
  on.exit(close(connection), add = TRUE)
  writeLines(lines, connection)
}

# ------------------------------- Read the CSV ---------------------------------

if (!file.exists(claims_path)) {
  stop_with_message(
    "Claims CSV not found at: ", claims_path,
    "\nUpdate claims_path near the top of this script."
  )
}

claims <- utils::read.csv(
  claims_path,
  na.strings = c("", "NA"),
  check.names = FALSE,
  fileEncoding = "UTF-8-BOM"
)

required_columns <- c(
  "claim_id",
  "in_scope",
  "frequentist_test",
  "f_value",
  "f_df1",
  "f_df2",
  "p_value",
  "n1",
  "n2",
  "n_total",
  "effect_size_type",
  "effect_size_value",
  "model_formula",
  "contrast_direction",
  "extraction_note",
  "raw_data_file"
)

require_columns(claims, required_columns, "claims")

target <- claims[claims$claim_id == target_claim_id, , drop = FALSE]

if (nrow(target) != 1L) {
  stop_with_message(
    "Expected exactly one row for ", target_claim_id,
    ", but found ", nrow(target), "."
  )
}

# ---------------------------- Extract stored values ---------------------------

in_scope <- as_logical_value(target$in_scope)
frequentist_test <- as.character(target$frequentist_test)
f_value <- as_numeric_value(target$f_value, "f_value")
f_df1 <- as_numeric_value(target$f_df1, "f_df1")
f_df2 <- as_numeric_value(target$f_df2, "f_df2")
stored_p <- as_numeric_value(target$p_value, "p_value")
n1 <- as_numeric_value(target$n1, "n1")
n2 <- as_numeric_value(target$n2, "n2")
n_total <- as_numeric_value(target$n_total, "n_total")
effect_size_type <- as.character(target$effect_size_type)
stored_effect_size <- as_numeric_value(
  target$effect_size_value,
  "effect_size_value"
)
model_formula <- as.character(target$model_formula)
contrast_direction <- as.character(target$contrast_direction)
extraction_note <- as.character(target$extraction_note)
raw_data_file <- as.character(target$raw_data_file)

# ---------------------- Derive the t-equivalent quantities --------------------

# When the numerator degrees of freedom equal 1, the F distribution is the
# square of the corresponding t distribution: F(1, df2) = t(df2)^2.
# F does not retain the sign, so only the absolute t value can be recovered.
t_abs_from_f <- sqrt(f_value)
t_df_from_f <- f_df2
p_from_f <- stats::pf(f_value, df1 = f_df1, df2 = f_df2, lower.tail = FALSE)
p_from_two_sided_t <- 2 * stats::pt(
  -abs(t_abs_from_f),
  df = t_df_from_f
)

# For an F test, partial eta squared can be recovered from F and its degrees of
# freedom as (F * df1) / (F * df1 + df2).
eta_p2_from_f <- (f_value * f_df1) / (f_value * f_df1 + f_df2)

# ------------------------------ Eligibility checks ----------------------------

formula_text <- paste(model_formula, collapse = " ")
contrast_text <- paste(contrast_direction, collapse = " ")
note_text <- paste(extraction_note, collapse = " ")

checks <- data.frame(
  check_id = c(
    "target_is_in_scope",
    "target_is_an_anova_effect",
    "numerator_df_equals_one",
    "two_nonempty_independent_groups_are_recorded",
    "group_sizes_sum_to_total_n",
    "error_df_equals_n_minus_two",
    "model_records_condition_as_the_between_subjects_factor",
    "target_is_the_between_subjects_condition_main_effect",
    "recorded_sample_has_two_condition_levels",
    "reported_p_matches_f_distribution",
    "f_and_two_sided_t_have_the_same_p_value",
    "reported_partial_eta_squared_matches_f_and_df"
  ),
  passed = c(
    in_scope,
    frequentist_test %in% c(
      "mixed_anova",
      "factorial_between_anova",
      "repeated_measures_anova",
      "one_way_anova"
    ),
    approximately_equal(f_df1, 1),
    is.finite(n1) && is.finite(n2) && n1 > 0 && n2 > 0,
    approximately_equal(n1 + n2, n_total),
    approximately_equal(f_df2, n_total - 2),
    grepl("BY\\s+Condition", formula_text, ignore.case = TRUE) &&
      grepl("/DESIGN\\s*=\\s*Condition", formula_text, ignore.case = TRUE),
    grepl("between-subjects main effect", contrast_text, ignore.case = TRUE) &&
      grepl("condition", contrast_text, ignore.case = TRUE),
    grepl("Condition levels\\s*=\\s*1\\s*;\\s*2", note_text, ignore.case = TRUE),
    approximately_equal(stored_p, p_from_f, tolerance_value = 1e-8),
    approximately_equal(p_from_f, p_from_two_sided_t, tolerance_value = 1e-12),
    effect_size_type == "eta_p2" &&
      approximately_equal(
        stored_effect_size,
        eta_p2_from_f,
        tolerance_value = 1e-8
      )
  ),
  evidence = c(
    paste0("in_scope = ", in_scope),
    paste0("frequentist_test = ", frequentist_test),
    paste0("f_df1 = ", format_number(f_df1)),
    paste0("n1 = ", format_number(n1), "; n2 = ", format_number(n2)),
    paste0(
      "n1 + n2 = ", format_number(n1 + n2),
      "; n_total = ", format_number(n_total)
    ),
    paste0(
      "f_df2 = ", format_number(f_df2),
      "; n_total - 2 = ", format_number(n_total - 2)
    ),
    model_formula,
    contrast_direction,
    extraction_note,
    paste0(
      "stored p = ", format_number(stored_p),
      "; p from F = ", format_number(p_from_f)
    ),
    paste0(
      "p from F = ", format_number(p_from_f),
      "; two-sided p from |t| = ", format_number(p_from_two_sided_t)
    ),
    paste0(
      "stored eta_p2 = ", format_number(stored_effect_size),
      "; eta_p2 from F and df = ", format_number(eta_p2_from_f)
    )
  ),
  stringsAsFactors = FALSE
)

metadata_checks_pass <- all(checks$passed)
raw_data_path_resolves <- !is.na(raw_data_file) &&
  nzchar(raw_data_file) &&
  file.exists(file.path(project_root, raw_data_file))

verification_level <- if (raw_data_path_resolves) {
  paste(
    "Metadata/model-structure verification completed.",
    "A raw-data file path also resolves, but this CSV-only script does not",
    "rerun the participant-level analysis."
  )
} else {
  paste(
    "Metadata/model-structure verification only.",
    "No accessible participant-level raw-data file was used."
  )
}

eligibility_decision <- if (metadata_checks_pass) {
  paste(
    "ELIGIBLE FOR WAVE 1 BASED ON THE RECORDED MODEL STRUCTURE:",
    "the target is a two-group between-subjects Condition main effect,",
    "df1 = 1, df2 = N - 2, and the reported F test is algebraically",
    "equivalent to a two-sided equal-variance independent-samples t-test."
  )
} else {
  paste(
    "DO NOT CLASSIFY AS WAVE 1 FROM THE CSV ALONE:",
    "one or more required structural checks failed."
  )
}

# ------------------------------- Write outputs --------------------------------

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

utils::write.csv(
  target,
  file.path(output_dir, "study_47_target_record.csv"),
  row.names = FALSE,
  na = ""
)

utils::write.csv(
  checks,
  file.path(output_dir, "study_47_wave1_metadata_checks.csv"),
  row.names = FALSE,
  na = ""
)

summary_lines <- c(
  "Study 47 Wave 1 eligibility check using the claims CSV only",
  "Generated by ChatGPT for the Bayesian reanalysis project.",
  "",
  paste0("Target claim: ", target_claim_id),
  paste0("Verification level: ", verification_level),
  "",
  "Stored result:",
  paste0(
    "F(", format_number(f_df1), ", ", format_number(f_df2), ") = ",
    format_number(f_value), ", p = ", format_number(stored_p)
  ),
  paste0(
    "n1 = ", format_number(n1),
    ", n2 = ", format_number(n2),
    ", N = ", format_number(n_total)
  ),
  "",
  "Derived t-equivalent result:",
  paste0(
    "|t|(", format_number(t_df_from_f), ") = ",
    format_number(t_abs_from_f)
  ),
  paste0("t^2 = ", format_number(t_abs_from_f^2)),
  paste0("Two-sided p from t = ", format_number(p_from_two_sided_t)),
  "",
  paste0("All metadata checks passed: ", metadata_checks_pass),
  paste0("Raw-data path resolves in this environment: ", raw_data_path_resolves),
  "",
  "Decision:",
  eligibility_decision,
  "",
  "Interpretive limitation:",
  paste(
    "The equality F(1, df) = t(df)^2 establishes algebraic equivalence once",
    "the target is known to be a single two-group contrast. The CSV records",
    "that this is the between-subjects Condition main effect from a two-group",
    "mixed design, with df2 = N - 2. However, without participant-level data",
    "this script cannot independently reconstruct the marginal outcome, rerun",
    "the SPSS mixed ANOVA, or confirm the complete-case rows directly."
  )
)

write_lines_utf8(
  summary_lines,
  file.path(output_dir, "study_47_wave1_metadata_summary.txt")
)

# ------------------------------ Console output --------------------------------

cat(paste(summary_lines, collapse = "\n"), "\n")
cat("\nValidation files written to:\n", normalizePath(output_dir), "\n")
