source("scripts/run_all_reproductions.R")
source("R/prepare/build_verified_results.R")
build_verified_results_draft()                
source("R/prepare/build_claims.R")
build_claims_draft()                         
file.copy("data/derived/claims_draft.csv", "data/derived/claims.csv", overwrite = TRUE)
message("Promoted claims_draft.csv -> claims.csv")
source("scripts/01_run_analysis.R")
source("scripts/02_run_figures.R")
message("00_run_all complete.")
